site_name: Linux Doc zh_CN Translation Status
site_description: Daily status of zh_CN translations of Linux kernel documentation
site_url: https://hust-open-atom-club.github.io/check_trans_update/
repo_url: https://github.com/hust-open-atom-club/check_trans_update
repo_name: hust-open-atom-club/check_trans_update

theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - i18n:
      docs_structure: suffix
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 中文
          build: true
          site_name: Linux 内核文档 zh_CN 翻译状态
          nav_translations:
            Overview: 概览
            Needs translation: 待翻译
            Needs update: 待更新

nav:
  - Overview: index.md
  - Needs translation: needs-translation.md
  - Needs update: needs-update.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
