site_name: Linux 内核中文文档翻译状态
site_description: Linux 内核中文文档翻译状态 · 每日自动更新
site_url: https://checktrans.openatom.club/
repo_url: https://github.com/hust-open-atom-club/check_trans_update
repo_name: hust-open-atom-club/check_trans_update

theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - i18n:
      docs_structure: suffix
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: zh
          default: true
          name: 中文
          build: true
        - locale: en
          name: English
          build: true
          site_name: Linux Doc zh_CN Translation Status
          nav_translations:
            概览: Overview
            待翻译: Needs translation
            待更新: Needs update

nav:
  - 概览: index.md
  - 待翻译: needs-translation.md
  - 待更新: needs-update.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
